# Created with WinGet Releaser v2 using Komac v1.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: gerardog.gsudo
PackageVersion: 2.5.1
InstallerLocale: en-US
InstallerType: wix
UpgradeBehavior: install
Commands:
- gsudo
- sudo
ReleaseDate: 2024-05-30
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/gerardog/gsudo/releases/download/v2.5.1/gsudo.setup.x86.msi
  InstallerSha256: 2D0D1A9940226B5451716A5FAC6452EF40C95F4C3B362F4F22427484B53273F2
  InstallerSwitches:
    InstallLocation: INSTALLFOLDER="<INSTALLPATH>"
  ProductCode: '{8975E360-D12F-4960-9729-B7C9168387DE}'
  AppsAndFeaturesEntries:
  - DisplayName: gsudo v2.5.1
    ProductCode: '{D3E82BF7-814D-40B8-9226-7124C00A0281}'
    UpgradeCode: '{567B5616-D362-484E-B6FF-7C1875CF0AEE}'
- Architecture: x86
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: x86/gsudo.exe
    PortableCommandAlias: gsudo
  - RelativeFilePath: x86/gsudo.exe
    PortableCommandAlias: sudo
  InstallerUrl: https://github.com/gerardog/gsudo/releases/download/v2.5.1/gsudo.setup.x86.msi
  InstallerSha256: 2D0D1A9940226B5451716A5FAC6452EF40C95F4C3B362F4F22427484B53273F2
  ProductCode: '{8975E360-D12F-4960-9729-B7C9168387DE}'
  AppsAndFeaturesEntries:
  - DisplayName: gsudo v2.5.1
    UpgradeCode: '{567B5616-D362-484E-B6FF-7C1875CF0AEE}'
- Architecture: x64
  InstallerUrl: https://github.com/gerardog/gsudo/releases/download/v2.5.1/gsudo.setup.x64.msi
  InstallerSha256: E7C13E323A04B568ECFEAB707A84279625C70036FBD9CE1AB41D0387990606C1
  InstallerSwitches:
    InstallLocation: INSTALLFOLDER="<INSTALLPATH>"
  ProductCode: '{EA9CC930-D8A0-4F45-BC61-19D65DA00641}'
  AppsAndFeaturesEntries:
  - DisplayName: gsudo v2.5.1
    ProductCode: '{513EE214-910B-4302-9A58-B75DCEFA4E7A}'
    UpgradeCode: '{567B5616-D362-484E-B6FF-7C1875CF0AEE}'
- Architecture: x64
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: x64/gsudo.exe
    PortableCommandAlias: gsudo
  - RelativeFilePath: x64/gsudo.exe
    PortableCommandAlias: sudo
  InstallerUrl: https://github.com/gerardog/gsudo/releases/download/v2.5.1/gsudo.setup.x64.msi
  InstallerSha256: E7C13E323A04B568ECFEAB707A84279625C70036FBD9CE1AB41D0387990606C1
  ProductCode: '{EA9CC930-D8A0-4F45-BC61-19D65DA00641}'
  AppsAndFeaturesEntries:
  - DisplayName: gsudo v2.5.1
    UpgradeCode: '{567B5616-D362-484E-B6FF-7C1875CF0AEE}'
- Architecture: arm64
  InstallerUrl: https://github.com/gerardog/gsudo/releases/download/v2.5.1/gsudo.setup.arm64.msi
  InstallerSha256: BF58ED4E72007CB37D30FE91658D28826D0D4AC2712DEBC545C8F82A2412BEE3
  InstallerSwitches:
    InstallLocation: INSTALLFOLDER="<INSTALLPATH>"
  ProductCode: '{EA92D85D-B2CF-478F-A141-749F3216F8AF}'
  AppsAndFeaturesEntries:
  - DisplayName: gsudo v2.5.1
    ProductCode: '{1245C6AA-EF42-4E1D-BD45-C53E155DD252}'
    UpgradeCode: '{567B5616-D362-484E-B6FF-7C1875CF0AEE}'
- Architecture: arm64
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: arm64/gsudo.exe
    PortableCommandAlias: gsudo
  - RelativeFilePath: arm64/gsudo.exe
    PortableCommandAlias: sudo
  InstallerUrl: https://github.com/gerardog/gsudo/releases/download/v2.5.1/gsudo.setup.arm64.msi
  InstallerSha256: BF58ED4E72007CB37D30FE91658D28826D0D4AC2712DEBC545C8F82A2412BEE3
  ProductCode: '{EA92D85D-B2CF-478F-A141-749F3216F8AF}'
  AppsAndFeaturesEntries:
  - DisplayName: gsudo v2.5.1
    UpgradeCode: '{567B5616-D362-484E-B6FF-7C1875CF0AEE}'
ManifestType: installer
ManifestVersion: 1.5.0
