# Created with YamlCreate.ps1 v2.1.3 using InputObject 🤖 $debug=QUSU.7-2-6
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.2.0.schema.json

PackageIdentifier: gerardog.gsudo
PackageVersion: 1.7.2-winget-releaser-test
MinimumOSVersion: 10.0.0.0
InstallerType: wix
Scope: machine
InstallerSwitches:
  Silent: /quiet /norestart
  SilentWithProgress: /passive /norestart
UpgradeBehavior: install
Commands:
- gsudo
- sudo
ReleaseDate: 2022-10-21
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/gerardog/gsudo/releases/download/v1.7.2-winget-releaser-test/gsudoSetup.msi
  InstallerSha256: CEC385CB43DE63D05A88BCCFDF51D4E11455DC2C9B3D42A2C699175EB75CC9BD
  ProductCode: '{D7EBF8EC-0C24-4376-8D3C-4AF02D64A32C}'
ManifestType: installer
ManifestVersion: 1.2.0
